### ISSUE TITLE
the test track not show 

### ISSUE THREAD

**Issue by shenweima** [cmdcolin/jbrowse_piechart#2]
http://202.194.139.32/jbrowse-1.12.3-release/?data=plugins/PiechartPlugin/test/data

![image](https://user-images.githubusercontent.com/8536868/75956622-3f487b00-5ef3-11ea-88ea-9b605da2d8fc.png)

**Comment by cmdcolin** [comment]
The sample configuration uses a shortcut for the config that only works on newer versions of jbrowse

I pushed a change to this repo to fix the config for older jbrowsers

**Comment by shenweima** [comment]
work, thanks.

**Comment by cmdcolin** [comment]
sure thing. let me know if any additional features can help :)
