### ISSUE TITLE
css file  in this plugin was missing ?

### ISSUE THREAD

**Issue by shenweima** [cmdcolin/jbrowse_piechart#6]
http://202.194.139.32/jbrowse-1.12.3-release/?data=Cadenza
![image](https://user-images.githubusercontent.com/8536868/114267465-57f85e00-9a2e-11eb-9da5-7419b3fcbf8a.png)

![image](https://user-images.githubusercontent.com/8536868/114267425-0e0f7800-9a2e-11eb-9ff8-9c2f3d32882f.png)

**Comment by cmdcolin** [comment]
@shenweima technically a plugin does not need a CSS file, jbrowse does try to fetch a css file for a plugin but if it does not exist you will get a 404 like you see but it should cause problem

are you seeing any other problems?

**Comment by cmdcolin** [comment]
I went ahead and pushed a blank css file to the repo to try to avoid the 404 error, but it's just a blank file

**Comment by shenweima** [comment]
Work
